# Generated by Django 4.2.11 on 2026-04-12 23:35

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Заголовок")),
                (
                    "summary",
                    models.TextField(
                        blank=True, default="", verbose_name="Краткое описание"
                    ),
                ),
                (
                    "full_text",
                    models.TextField(
                        blank=True, default="", verbose_name="Полный текст"
                    ),
                ),
                (
                    "is_significant",
                    models.BooleanField(default=False, verbose_name="Значимая (ML)"),
                ),
                (
                    "significance_level",
                    models.CharField(
                        choices=[
                            ("HIGH", "Высокий"),
                            ("MEDIUM", "Средний"),
                            ("LOW", "Низкий"),
                        ],
                        default="LOW",
                        max_length=10,
                        verbose_name="Уровень значимости",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(default=0.0, verbose_name="Confidence score ML"),
                ),
                (
                    "needs_moderation",
                    models.BooleanField(
                        default=False, verbose_name="Требует модерации"
                    ),
                ),
                (
                    "is_unconfirmed",
                    models.BooleanField(
                        default=False, verbose_name="Неподтверждённый слух"
                    ),
                ),
                (
                    "original_url",
                    models.URLField(max_length=1000, verbose_name="Ссылка на оригинал"),
                ),
                ("published_at", models.DateTimeField(verbose_name="Дата публикации")),
                (
                    "processed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата обработки"
                    ),
                ),
                (
                    "title_hash",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Хеш заголовка"
                    ),
                ),
                (
                    "assets",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Затрагиваемые активы"
                    ),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("macro", "Макроэкономика"),
                            ("corporate", "Корпоративные события"),
                            ("regulatory", "Регуляторные решения"),
                            ("market", "Рыночные события"),
                            ("geopolitics", "Геополитика"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="NewsSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("url", models.URLField(verbose_name="URL")),
                (
                    "tier",
                    models.IntegerField(
                        choices=[
                            (1, "Официальный регулятор"),
                            (2, "Информагентство"),
                            (3, "Деловые СМИ"),
                            (4, "Корпоративные раскрытия"),
                        ],
                        verbose_name="Уровень доверия",
                    ),
                ),
                (
                    "feed_url",
                    models.URLField(
                        blank=True, default="", verbose_name="URL RSS-фида"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "last_parsed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последний парсинг"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Источник",
                "verbose_name_plural": "Источники",
            },
        ),
        migrations.CreateModel(
            name="NewsCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "articles",
                    models.ManyToManyField(
                        related_name="clusters",
                        to="news.newsarticle",
                        verbose_name="Дубликаты",
                    ),
                ),
                (
                    "leader_article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cluster_leader",
                        to="news.newsarticle",
                        verbose_name="Основная новость",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кластер новостей",
                "verbose_name_plural": "Кластеры новостей",
            },
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="news.newscategory",
                verbose_name="Категория",
            ),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="articles",
                to="news.newssource",
                verbose_name="Источник",
            ),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(
                fields=["-published_at"], name="news_newsar_publish_db2481_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(
                fields=["significance_level"], name="news_newsar_signifi_8d93b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(
                fields=["source"], name="news_newsar_source__5f0f01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(
                fields=["category"], name="news_newsar_categor_236c31_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(
                fields=["title_hash"], name="news_newsar_title_h_1b4d6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="idx_search_vector"
            ),
        ),
    ]
