# Generated by Django 4.2.11 on 2026-04-12 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="userbookmark",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="news.newsarticle"
            ),
        ),
        migrations.AddField(
            model_name="userbookmark",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usersubscription",
            unique_together={("user", "category", "asset_ticker")},
        ),
        migrations.AlterUniqueTogether(
            name="userbookmark",
            unique_together={("user", "article")},
        ),
    ]
